#!/bin/bash
#
# Shellscript-based poor man's version of:
#
#   - https://hynek.me/articles/python-app-deployment-with-native-packages/
#   - https://parcel.readthedocs.org/
#
# Status: Work in progress
#
# Synopsis::
#
#   fpm-package kotori stretch 0.21.1
#

NAME=$1
DISTRIBUTION=$2
VERSION=$3

echo "Building package $NAME-$VERSION for ${DISTRIBUTION}"

# Build Debian package
mkdir -p ./dist
fpm \
    -s dir -t deb \
    \
    --name ${NAME} \
    --version ${VERSION} \
	--iteration 1~${DISTRIBUTION} \
	\
	--deb-user kotori \
	--deb-group kotori \
	--no-deb-use-file-permissions \
	--no-python-obey-requirements-txt \
	--no-python-dependencies \
	--depends "python2.7" \
	--deb-recommends "influxdb, mosquitto, mosquitto-clients, grafana, mongodb" \
	--deb-recommends "python-requests, python-openssl, python-cryptography, python-certifi" \
	--deb-recommends "python-numpy, python-scipy, python-matplotlib, python-tables, python-netcdf4" \
	--deb-recommends "libatlas3-base, libopenblas-base, liblapack3, libhdf5-100, libnetcdf-c++4, libnetcdf11" \
	--deb-recommends "liblzo2-2, libbz2-1.0, fonts-humor-sans" \
	--provides "kotori" \
	--provides "${NAME}" \
	--maintainer "andreas.motl@elmyra.de" \
	--license "AGPL 3, EUPL 1.2" \
	--deb-changelog CHANGES.rst \
	--deb-meta-file README.rst \
	--description "Kotori data acquisition, routing and graphing toolkit" \
	--url "https://getkotori.org/" \
    \
    --package ./dist/ \
    --config-files "/etc/kotori" \
    --deb-default ./packaging/etc/default \
    --before-install ./packaging/scripts/before-install \
    --after-install ./packaging/scripts/after-install \
    --before-remove ./packaging/scripts/before-remove \
    --verbose \
    --force \
    ${venv}/=/opt/kotori \
    ./etc/production.ini=/etc/kotori/kotori.ini \
    ./etc/examples/=/etc/kotori/examples \
    ./packaging/systemd/kotori.service=/usr/lib/systemd/system/kotori.service


# Optionally
#		--debug \


# Might use again when building from feature branches or other references
#--deb-field 'Branch: $(branch) Commit: $(commit)' \
#version  := $(shell python setup.py --version)



# -------------------
# Development options
# -------------------

# On your fingertips (enable on demand)


# general debugging
#		--debug \

# don't delete working directory (to introspect the cruft in case something went wrong)
#		--debug-workspace \

# we don't prefix, instead use the convenient mapping syntax {source}={target}
#		--prefix /opt/kotori \

# we don't set any architecture, let the package builder do it
#		--architecture noarch \

# there are currently just --deb-init and --deb-upstart options for designating an init- or upstart script
# we already use systemd

# Add FILEPATH as /etc/default configuration
#		--deb-default abc \

# amend the shebang of scripts
#	--python-scripts-executable '/usr/bin/env python' \

# Add custom fields to DEBIAN/control file
#		--deb-field 'Branch: master Commit: deadbeef' \
